ALTER TABLE books
    ADD COLUMN subtitle VARCHAR(255) NOT NULL,
    ADD COLUMN publisher VARCHAR(255) NOT NULL,
    ADD COLUMN isbn13 VARCHAR(13) NOT NULL UNIQUE,
    ADD COLUMN price DECIMAL(5, 2) NOT NULL,
    ADD COLUMN year INT NOT NULL,
    ADD COLUMN rating INT DEFAULT 0 CHECK (rating >= 1 AND rating <= 5);

